adds test for elixir-mix
updates build to use ghc 8.10.5

ci build to use ghc 8.10

uses haskell action for ci build

attempting fix the build

attempting fix the build #2

attempting fix the build #3

attempting fix the build - with container image

attempting fix the build

simplifies build workflow

attempt to mock vendor deps

adds pre build script

updates permission of elixir build script

adds rebar into elixir build script

skips failing tests

updates nix channel

unskips go and maven tests, and removes build script from rails

updates ruby/rails submodule

fixes build error

updates scala integration tests

adds comment for build workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -14,13 +14,24 @@ jobs:
       run: |
         echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV
 
-    - uses: actions/setup-haskell@v1.1
+    # stack is enabled here to prohibit haskell/actions/setup@v1 from updating cabal. 
+    # Ref: https://github.com/haskell/actions/blob/main/setup/src/setup-haskell.ts#L49
+    - uses: haskell/actions/setup@v1
+      id: setup-haskell
+      name: Setup ghc/cabal (non-alpine)
       with:
-        ghc-version: '8.10'
+        ghc-version: '8.10.5'
+        enable-stack: true 
+
+    - name: Debugging information
+      run: |
+        ghc --version || echo "no ghc"
+        cabal --version || echo "no cabal"
+        ghcup --version || echo "no ghcup"
 
     - uses: cachix/install-nix-action@v10
       with:
-        nix_path: nixpkgs=channel:nixos-unstable
+        nix_path: nixpkgs=channel:nixos-20.09
 
     - uses: actions/cache@v1
       name: Cache cabal store
@@ -30,6 +41,19 @@ jobs:
           ${{ runner.os }}-cabal-cache-
           ${{ runner.os }}-
         path: ${{ steps.setup-haskell.outputs.cabal-store || '~/.cabal/store' }}
+
+    # FIXME: Find better approach to attain vendor dependencies of spectrometer.
+    # Since spectrometer's distribution does not include required extra-source-files,
+    # to successfully build spectrometer test project, mock vendor dependencies.
+    - name: Get Spectrometer's vendor dependencies
+      run: |
+        echo "SPECTROMETERTEST_DIR=`pwd`" >> $GITHUB_ENV
+        cabal update || cd "$(dirname "$(find ./dist-newstyle -type f -name spectrometer.cabal | head -1)")" || echo "failed to find spectrometer src package"
+        mkdir vendor
+        touch vendor/cliv1
+        touch vendor/syft
+        touch vendor/wiggins 
+        cd $SPECTROMETERTEST_DIR
 
     - name: Build
       run: |
